# Configuration file for golangci-lint

version: "2"

linters:
    default: all
    disable:
        - exhaustruct
        - funlen
        - depguard
        - forbidigo
        - wsl
    settings:
        lll:
            line-length: 140
            tab-width: 4
        wsl_v5:
            allow-first-in-block: true
            allow-whole-block: false
            branch-max-lines: 2
