name: Go

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23.3"

            - name: Lint
              uses: golangci/golangci-lint-action@v8.0.0
              with:
                  args: "-c .golangci.yaml"

            - name: Build
              run: go build .
